use_frameworks!

platform :ios, '9.0'

target 'PuyoBuilder_Example' do
  pod 'PuyoBuilder', :path => '../'
#  pod 'Puyopuyo', '3.0.0-beta-2'
  pod 'Puyopuyo', :path => '/Users/j/Documents/git-repo/puyopuyo'
  pod 'HandyJSON'

  target 'PuyoBuilder_Tests' do
    inherit! :search_paths

    
  end
end
